/**
 * * Custom Application Tokens
 * */
// Define token names here
#define CREATOR_AUTOJOIN_ENABLED        (0x1020)
#define CREATOR_NWK_STEERING_PRIMARY_CHANNEL_MASK        (0x1028)
#define CREATOR_NWK_STEERING_SECONDARY_CHANNEL_MASK       (0x1032)
#define CREATOR_NWK_CREATOR_PRIMARY_CHANNEL_MASK        (0x1033)
#define CREATOR_NWK_CREATOR_SECONDARY_CHANNEL_MASK       (0x1034)

#ifdef DEFINETYPES
// Include or define any typedef for tokens here
#endif //DEFINETYPES
#ifdef DEFINETOKENS
// Define the actual token storage information here
DEFINE_BASIC_TOKEN(AUTOJOIN_ENABLED, uint8_t, 0x00)
DEFINE_BASIC_TOKEN(NWK_STEERING_PRIMARY_CHANNEL_MASK, uint32_t, 0x0318c800UL)
DEFINE_BASIC_TOKEN(NWK_STEERING_SECONDARY_CHANNEL_MASK, uint32_t, 0x07FFF800UL)
DEFINE_BASIC_TOKEN(NWK_CREATOR_PRIMARY_CHANNEL_MASK, uint32_t, 0x02108800UL)
DEFINE_BASIC_TOKEN(NWK_CREATOR_SECONDARY_CHANNEL_MASK, uint32_t, 0x07FFF800UL)

#endif //DEFINETOKENS
